"""'Initial'

Revision ID: 803b55635fce
Revises: 
Create Date: 2023-02-05 19:38:41.616421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '803b55635fce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mails', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('mails', 'recipient_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_unique_constraint(None, 'mails', ['id'])
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_constraint(None, 'mails', type_='unique')
    op.alter_column('mails', 'recipient_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('mails', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
