"""Initial

Revision ID: 8dbf7afeeec0
Revises: 803b55635fce
Create Date: 2023-02-07 20:30:41.785060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbf7afeeec0'
down_revision = '803b55635fce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('mails', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mails', 'read')
    op.drop_column('mails', 'title')
    # ### end Alembic commands ###
